### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by cangwang** [uber/okbuck#181]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/air/Desktop/Android/MyJob/Muxer/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'Muxer'.
> java.lang.UnsupportedClassVersionError: com/github/okbuilds/okbuck/OkBuckGradlePlugin : Unsupported major.minor version 52.0

I have run the project in Java jdk1.8.0_91, but it show this error.Please help me to solve this problem,thx

**Comment by kageiit** [comment]
Can you provide a small repro project that can reproduce this error? Have not been able to repro this using jdk1.8

**Comment by 2BAB** [comment]
@cangwang Just Using JDK 1.8, make sure `java -version` && `javac -help` are working.

**Comment by cwoodwar6** [comment]
For what its worth, I've had the same issue.

**Comment by kageiit** [comment]
what plugin are you using. the new artifact is `com.uber:okbuck:0.7.0`. Can you please try that

**Comment by cwoodwar6** [comment]
This issue occurred for me when I was using Gradle 2.1.3 and using version 0.5.0 of the plugin. The error only occurred when trying to Gradle sync in Android studio. Since then I've updated to Gradle 2.2.0 and the 0.7.0 plugin, now the issue seems to be resolved.

Not sure what @cangwang's experience is but making both of those updates worked for me.

**Comment by kageiit** [comment]
@cangwang can you try the suggested workaround. Feel free to re-open if this still happens after that
