### ISSUE TITLE
okBuck fails silently on u2020

### ISSUE THREAD

**Issue by dsyang** [uber/okbuck#224]
Mostly a duplicate of #223 because of the new questions I raised after the issue was closed (not sure how to re-open a close issue or if thats even possible).

Sorry for the thrash!

**Comment by kageiit** [comment]
u2020 is actually a very simple app to try okbuck on (with regards to build configuration)

I just had to make it have a top level build.gradle file since okbuck only operates on subprojects by default

https://github.com/kageiit/u2020/tree/okbuck

It generates buck files correctly now. The actual build has issues with R.id values being treated as final etc. which need to be tweaked with buck projects as usual

**Comment by dsyang** [comment]
I figured it was something small since it's not that complex of an app.  The error messages just didn't make any since so I couldn't figure out what was wrong. Thanks for looking into it @kageiit.  

Do you think we can update the error message or have a check to tell people you need a top-level build.gradle?

**Comment by dsyang** [comment]
Or make okBuck work with 1 project projects :)

**Comment by kageiit** [comment]
It works with one project projects

There just needs to be a top level build.gradle right now.

Without that would need to modify the okbuck extensions

Take a look at the buck projects extension option. That's where you can change the default from being subproject to whatever projects you like

**Comment by kageiit** [comment]
Closing this as workaround was posted for u2020 already. Feel free to open a PR if you would like to support okbuck for projects with no subprojects
