### ISSUE TITLE
Comparable dependency declaration generates different BUCK files

### ISSUE THREAD

**Issue by cwoodwar6** [uber/okbuck#248]
Declaring a dependency by using an array such as:
```
ext.deps = [
    dagger2: [
        dagger2: "com.google.dagger:dagger:2.7",
        dagger2compiler: "com.google.dagger:dagger:2.7"
    ]
]

compile deps.dagger2.dagger2
annotationProcessor deps.dagger2.dagger2compiler
```
Provides a different generated BUCK file than when using the dependency hardcoded such as:
```
compile 'com.google.dagger:dagger:2.7'
annotationProcessor 'com.google.dagger:dagger-compiler:2.7'
```

I've created a demo project here:
https://github.com/cwoodwar6/okbuck-test-project

If you run `./buckw build app:src_debug` and compare app/BUCK with DEPS_BUCK they should be identical.

Make the following change in app/build.gradle:
```
//  compile deps.dagger2.dagger2
//  annotationProcessor deps.dagger2.dagger2compiler

  compile 'com.google.dagger:dagger:2.7'
  annotationProcessor 'com.google.dagger:dagger-compiler:2.7'
```
Run `./buckw build app:src_debug` again and compare app/BUCK to HARDCODE_BUCK. 

The results for both should be the same. But if you compare DEPS_BUCK to HARDCODE_BUCK, they are not identical.

I would expect that however you declare dependencies, the result should be the same generated BUCK file.

**Comment by kageiit** [comment]
There is a bug in your test project
ext is project local
so your extension block only ever applied to the root project
if you look at the sample okbuck project configuration, the `dependencies.gradle` script is applied to all subprojects as well
https://github.com/uber/okbuck/blob/master/build.gradle#L16

**Comment by cwoodwar6** [comment]
If that were the case, why is it able to resolve dependencies in app/build.gradle? Wouldn't moving ```ext.deps = [
    dagger2: [
        dagger2: "com.google.dagger:dagger:2.7",
        dagger2compiler: "com.google.dagger:dagger:2.7"
    ]
]``` into app/build.gradle resolve the issue if it it only applies locally? That is not the case I am seeing.

**Comment by cwoodwar6** [comment]
Your suggested fix also didn't seem to fix the issue: https://github.com/cwoodwar6/okbuck-test-project/commit/b988ef4a69a857120a0cc35ce3251e109aa3dab7

**Comment by kageiit** [comment]
This issue is

https://github.com/cwoodwar6/okbuck-test-project/commit/b988ef4a69a857120a0cc35ce3251e109aa3dab7#diff-3b9a217ffab4682c5a1776933687741fR4

`deps.dagger2.dagger2compiler` is not the same as `com.google.dagger:dagger-compiler:2.7`

The dependencies.gradle file has it set to `com.google.dagger:dagger:2.7` which is the wrong artifact. okbuck only adds annotation processors if it can find them as defined in the jar manifest entry. dagger runtime does not contain the annotation processor. the compiler artifact does.

Changing the artifact consumed in dependencies.gradle makes it work as expected

**Comment by cwoodwar6** [comment]
Doh, good catch.
