### ISSUE TITLE
Watchman not running ./gradlew okBuck automatically

### ISSUE THREAD

**Issue by Maragues** [uber/okbuck#254]
I built *./buck targets* and the first time it did show targets. Then I did a *./gradlew clean* and the *app/build* folder dissappeared. *Watchman* is installed, so I was hoping that it automatically run *./gradlew okbuck*, but it didn't

*./buck targets* shows an error message

    BUILD FAILED: //app:bin_devRelease: parameter 'proguardConfig': no such file or directory 'app/build/okbuck/devRelease/proguard.pro'

Running *./gradlew okbuck* creates all files needed.

How can I debug why *watchman* isn't doing its job?

**Comment by kageiit** [comment]
I think the issue is that watchman is not really watching for changes in gradle build folders. If you find having to run `./gradlew clean` often I would suggest adding this to your root build.gradle

```
task clean(type: Delete) {
  delete rootProject.buildDir
}
```

This will delete the top level `build` folder which `buckw` does monitor to decide whether to run okbuck again or not.
