### ISSUE TITLE
Support for protobuf-gradle-plugin

### ISSUE THREAD

**Issue by gengjiawen** [uber/okbuck#260]
plugin location: https://github.com/google/protobuf-gradle-plugin

I tried somthing like sqldelight in this repo https://github.com/Piasy/AndroidTDDBootStrap. But with no luck.Maybe the task is generated dynamically using dsl.

**Comment by kageiit** [comment]
Okbuck cannot support third party plugins directly because running them inside buck can be bad due to

- Not knowing when exactly to invalidate such rules
- increased build times due to multiple gradle invocations

Now okbuck relies on the gradle tasks to be called directly by the consumer before the `okbuck` task runs. An example of how this is done with sqldelight is here: https://github.com/uber/okbuck/blob/master/build.gradle#L100

The example essentially grabs the sqldelight gen tasks and runs them before okbuck can run so that the sunsequent `okbuck` task run can recognize the generated files as inputs to the generated buck rules. This is the recommended approach for third party gradle plugin integrations and especially for plugins that generate sources.

**Comment by kageiit** [comment]
Closing since support will not be added from within okbuck
