### ISSUE TITLE
"Resources not found" for `src/debug` code referencing `src/main` resources

### ISSUE THREAD

**Issue by tmelz** [uber/okbuck#318]
```
➜  android git:(master) ✗ ./buckw build //Yelp:res_debug
The following resources were not found when processing /android/Yelp/src/debug/res:
RDotTxtEntry{idType=int, type=drawable, name=close_icon, idValue=0x00000000}
RDotTxtEntry{idType=int, type=style, name=ConfigButton, idValue=0x00000000}

BUILD FAILED: //Yelp:res_debug failed with exit code 1:
generate_resource_ids
```
These are resources stored in `Yelp/src/main/res`, referenced by code in `Yelp/src/debug/`. Working with @raviagarwal7, we found that adding `:res_main` to the dependencies of `:res_debug` in `Yelp/BUCK` resolves the issue.

**Comment by kageiit** [comment]
@tmelz res_main and res_debug cannot depend on each other directly because they are part of the same sourceset i.e resources in debug can refer to those in main and those in main can refer to debug. This is possible in gradle due to the variant concept, but not in buck because there is no concept of variants thats part of the build system. This can be worked around by the method specified in https://github.com/uber/okbuck/issues/221 i.e extracting such resources into a separate gradle modules and making the dependency explicitly so that okbuck can pickup on that

**Comment by tmelz** [comment]
Thanks for the info! Looks like I should read up on the "variant concept". For now, just copying the files into `src/debug` is a good enough workaround for me.

**Comment by tmillettweather** [comment]
Was this done in the android_resource block in the BUCK file?

"These are resources stored in Yelp/src/main/res, referenced by code in Yelp/src/debug/. Working with @raviagarwal7, we found that adding :res_main to the dependencies of :res_debug in Yelp/BUCK resolves the issue."
