### ISSUE TITLE
Product flavor with duplicate exportedDeps

### ISSUE THREAD

**Issue by Macarse** [uber/okbuck#332]
I am trying okbuck for the first time in a pretty big app.
I am using `com.uber:okbuck:0.14.3`

When I run `./buckw targets` I get:

```
BUILD SUCCESSFUL

Total time: 9.274 secs
Task timings:
   1593ms  :okbuckClean
    100ms  :setupOkbuck
   2328ms  :MyApp:okbuck

 PROCEEDING WITH BUCK 

Not using buckd because watchman isn't installed.
[+] PARSING BUCK FILES...25.7s
BUILD FAILED: //MyApp:src_productFlavorBuildType: parameter 'exportedDeps': duplicate element "//MyApp:productFlavorBuildType_aidls"
```

Inside the BUCK generated file I see:

```
android_library(
	name = 'src_productFlavorBuildType',
	srcs = glob([
		'src-gen-dao/**/*.java',
		'src/**/*.java',
		'build-types/buildtype/java/**/*.java',
	]),
	manifest = 'build/okbuck/productFlavorBuildType/AndroidManifest.xml',
	annotation_processors = [
		'butterknife.compiler.ButterKnifeProcessor',
		'com.bluelinelabs.logansquare.processor.JsonAnnotationProcessor',
	],
	annotation_processor_deps = [
		':apt_jar_productFlavorBuildType',
	],
	exported_deps = [
		':productFlavorBuildType_aidls',
		':productFlavorBuildType_aidls',
	],
	source = '7',
	target = '7',

...
```

Any idea what could be the problem?

**Comment by kageiit** [comment]
Can you try to extract all your aidl files to a separate gradle module and have your app project depend on it? This might be a case we have not encountered yet. if you can create a small sample or make a branch on okbuck samples that repros the errors, we can dig more into it. Thanks!

**Comment by Macarse** [comment]
@kageiit I found the problem in my project but I couldn't reproduce in the okbuck's samples :(

In my project I have:
```
aidl.srcDirs = ['src-gen-dao', 'src', 'apt_generated']
```

`src-gen-dao` is the folder of the generated java files from GreenDao. GreenDao doesn't generate AIDLs, so I changed that line to:

```
aidl.srcDirs = ['src', 'apt_generated']
```

and this unblocked me.

Perhaps two different src folders with code in them generate two `exported_deps`?

**Comment by kageiit** [comment]
@Macarse it seems you are right, we currently try to generate separate rules for each aidl source directory, but name them the same, which leads to the conflict.

The fix is to consume all aidl sources at once as part of a single rule. Thanks for reporting back. I will push up a PR and would appreciate it if you can test it out on your project locally.

**Comment by Macarse** [comment]
@kageiit 👍

**Comment by kageiit** [comment]
@Macarse to use https://github.com/uber/okbuck/pull/341 locally

- Pull it down
- Change version in `buildSrc/build.gradle` to something like a snpashot
- Run `./gradlew plugin:publishToMavenLocal` to pload local okbuck to mavenLocal
- Consume it in your project and run your okbuck/buck commands again

Please report back if your issue is fixed before you needed to make changes

**Comment by Macarse** [comment]
Nope, it didn't work.

I get:

```
Parse error for build file /..../myProject/MyApp/BUCK:
Syntax error on line 19:
gen_productFlavorBuildType_src-gen-dao_aidls = []
````

PS: I am going to bed, I will try tomorrow if you have another fix. Cheers!

**Comment by kageiit** [comment]
I think that is because `-` is not allowed as a valid character in `BUCK` files for a rule name. I replaced `-` with `_` for now.

**Comment by kageiit** [comment]
@Macarse any luck with the latest commit? I pushed updates to #341

**Comment by Macarse** [comment]
@kageiit Sorry for the delay. You changed worked! 👍
