### ISSUE TITLE
Buck parsing files taking too long

### ISSUE THREAD

**Issue by Macarse** [uber/okbuck#377]
@kageiit in the SF meetup you mentioned there was a way of just running a single build type. Can you give an example?

**Comment by kageiit** [comment]
You can do something like

```
android {
            variantFilter {
                if (!(it.buildType.name == "debug")) {
                    it.ignore = true
                }
            }
        }
```

That will disable all non debug build Types. If you want only one flavor or variant, you can use `it.flavor` or `it.name` instead

**Comment by Macarse** [comment]
@kageiit interesting, thanks.

There is no way to move that logic to okBuck somehow?
Or another way of using this trick without modifying gradle files every time I want to build something different?

**Comment by kageiit** [comment]
This is not something okbuck should enforce because it has no idea what a consumer has in their gradle configuration with regards to custom flavors and build types.

You can put all your configuration behind project/system flags and enable them as needed. In any case, the gradle build optimization itself is outside the scope of okbuck. We will be publishing some docs around best practices and more samples soon so users can adapt them to their needs. Keep an eye out for those in the wiki!

**Comment by Macarse** [comment]
oh, that's very clever. Are you doing with env vars?

**Comment by kageiit** [comment]
Yes env vars or project properties both work fine
