### ISSUE TITLE
OkBuck and Crashlytics don't play well together

### ISSUE THREAD

**Issue by vanniktech** [uber/okbuck#378]
Repro steps:

1. Add Crashlytics to your project
2. `./buckw build appRelease`
3. Open the app
4. Crash appears 

```
java.io.FileNotFoundException: crashlytics-build.properties
 at android.content.res.AssetManager.openAsset(Native Method)
 at android.content.res.AssetManager.open(AssetManager.java:347)
 at android.content.res.AssetManager.open(AssetManager.java:321)
 at com.a.a.b.c.b(Beta.java:172)
 at com.a.a.b.c.d(Beta.java:6075)
 at io.fabric.sdk.android.g.e(InitializationTask.java:1063)
 at io.fabric.sdk.android.services.concurrency.a$2.call(AsyncTask.java:311)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 at java.lang.Thread.run(Thread.java:761)
```

Gradle puts the `crashlytics-build.properties` where it belongs. OkBuck does not since Plugins are not handled by default. Is there a way to make this work?

**Comment by kageiit** [comment]
Ya, you can invoke the crashlytics task before the okbuck task, or better yet, if this is only for release build, check the contents of whats inside that file and check it in where it belongs so buck can pick it up

**Comment by MrHadiSatrio** [comment]
Sorry for necro-ing this old thread, but suppose that I know what Fabric is putting into the file and where it's storing it in the APK, what should I do next?

FYI, this is what the plugin generates (under `/app/build/generated/fabric/res/[CURR_BUILD_VARIANT]/values/com_crashlytics_build_id.xml`):
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<resources xmlns:tools="http://schemas.android.com/tools">
<string tools:ignore="UnusedResources,TypographyDashes" name="com.crashlytics.android.build_id" translatable="false">xxx-xxx-xxx-xxx</string>
</resources>
```

...and this is what it ends up putting in the APK (under `/assets/crashlytics-build.properties`):
```
version_name=[YOUR_VERSION_NAME]
package_name=[YOUR_PACKAGE_NAME]
build_id=[GENERATED_BUILD_ID]
version_code=[YOUR_VERSION_CODE]
app_name=[YOUR_APP_NAME]
```

How exactly do we tell OkBuck/Buck to sort this out given the above?

**Comment by kageiit** [comment]
Maybe @jakeouellette can comment on this?

**Comment by jakeouellette** [comment]
Hi @kageiit , Have never used OkBuck, so I'm afraid I don't have a lot of insight on your side, but I can tell you what our plugin does -- if it helps meet in the middle!

Our plugin calls project.android.applicationVariants.all, then adds a bunch of tasks between some existing android tasks from the Android plugin. It won't do that if the android plugin doesn't exist, or if those tasks aren't available off its object model. So I'd check the logs to see if this is happening. That assumes that OkBuck changes nothing about the gradle build -- but that seems kind-of a silly assumption, it's supposed to be Buck right? and speed up your build a whole lot?

If that's the case you'd probably need to manually invoke our tasks and pass in the appropriate things.

Our plugin wasn't really designed for that (unfortunately, I learned how to build extensible Gradle plugins because of some of the lacking extensibility of that plugin -- my last Gradle summit talk gives some ideas on how to avoid that issue) That said, there is definitely a workaround to invoke our tasks outside of the normal integration that is easier and more correct than simply trying to output those files manually.

If someone's interested in trying to build that workaround for OkBuck, drop a note here and I'd be happy to point you in the right direction with probably more details than you're interested in reading.

**Comment by kageiit** [comment]
Talked to  @jakeouellette on slack. He said he would put up some documentation on how to invoke the fabric plugin like a standalone jar. We can then figure out how to integrate it with okbuck and buck.

**Comment by jakeouellette** [comment]
Hey folks! ( @kageiit & @vanniktech )
I have put together a gist of the shell script I was describing in Slack, here:
https://gist.github.com/jakeouellette/42f0615f9c5c557b540dac7ae639a6f9

I know very little about running buck (!), but if someone ends up tackling this, let me know if anything's confusing!

**Comment by jakeouellette** [comment]
Also, I haven't tested this extensively -- so no guarantees I didn't do anything silly in this script. If there's any non-obvious errors, I can assist getting across the finish line.

**Comment by kageiit** [comment]
@naveenOnarayanan any interest in porting over our internal crashlytics bits to here with some tweaks?

**Comment by vanniktech** [comment]
Has there been any progress on the porting?

**Comment by vanniktech** [comment]
The 'original' Crashlytics itself is deprecated nowadays.
