### ISSUE TITLE
how to set kapt arguments ?

### ISSUE THREAD

**Issue by taotaoping** [uber/okbuck#681]
I am using objectbox in a mixed kotlin/java module, and it need a kapt argument named "objectbox.modelPath",  how to set kapt arguments with okbuck?

**Comment by cwoodwar6** [comment]
[`extra_kotlinc_arguments`](https://buckbuild.com/rule/android_library.html#extra_kotlinc_arguments) was created for this purpose. However, the issue with using that directly is that it won't be included as part of the kotlinc arguments that Buck provides to use kapt. You would likely have to make a modification to Buck in order to be able to provide additional kapt arguments. 

You COULD alternatively provide `extra_kotlinc_arguments` for exactly everything you need to invoke kapt and don't let Buck configure the annotation processor for you.
