### ISSUE TITLE
Support Kotlin plugin's api/implementation configurations

### ISSUE THREAD

**Issue by ZacSweers** [uber/okbuck#813]
Kotlin 1.3.11? brought it up to parity with the `java-library` plugin, but okbuck will still effectively treat all of these as `implementation` dependencies even if they're designated `api`. It should have feature parity and export `api` deps

**Comment by kageiit** [comment]
Can you make a pr with a repro/example of the issue?

We currently have an example in okbuck repo - https://github.com/uber/okbuck/blob/master/libraries/kotlinandroidlibrary/build.gradle#L12

Consumed by another module - https://github.com/uber/okbuck/blob/master/app/build.gradle#L71

The generated buck file for app contains kotlin std lib in its dependency list as expected of an api dep

**Comment by kageiit** [comment]
The issue is with usage of the api configuration without applying the java-library or any of the AGP plugins.

The mechanism to consume transitively, deps of  api configurations are implemented separately by both the java-library plugin from gradle and the various library plugins from AGP. The kotlin plugin only applies the java plugin and not the java-library plugin internally which is why you are seeing this behavior.

The fix is basically to add apply plugin: "java-library" to the kotlin module when using api configurations

**Comment by ZacSweers** [comment]
The Kotlin plugin added API/implementation natively starting in 1.3.1x. Why would you need to then apply java-library on top of it? Also what does AGP have to do with java-library?
