### ISSUE TITLE
OkBuck is incompatible with AGP 3.4.0

### ISSUE THREAD

**Issue by inez** [uber/okbuck#840]
OkBuck in current version (0.47.1) is incompatible with AGP in version 3.4.0.
OkBuck contains call to `getNdkCompile` in `buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidAppTarget.java`, but that method does not exist anymore on `com.android.build.gradle.api.BaseVariant`. Perhaps `getNdkCompileProvider()` should be used.

**Comment by rifqimfahmi** [comment]
any follow up for this yet? I believe I am also having a similar problem.

```
* What went wrong:
Execution failed for task ':app:okbuck'.
> com.android.build.gradle.api.BaseVariant.getNdkCompile()Lcom/android/build/gradle/tasks/NdkCompile;

```

**Comment by inez** [comment]
@rifqimfahmi As a workaround you might want to fork and apply patch similar to this: https://github.com/uber/okbuck/pull/841/commits/ce5f97fa5d28e00c1fb3ea8f045a4ccf2b8531b3

**Comment by omegasoft7** [comment]
I have the same issue! When I downgraded `3.2.1` i is working just fine now.

**Comment by arnavzoman** [comment]
When will this be part of a released version of OkBuck ?

**Comment by tobrun** [comment]
Any updates on this?

**Comment by ilya-shknaj** [comment]
Issue still reproducing with latest 3.5.3 gradle plugin

**Comment by stevenovack** [comment]
I'm hitting the same problem.

**Comment by s1rius** [comment]
@kageiit Sorry to bother you, this issue is still reproducing with latest 3.6.1 gradle plugin

**Comment by onlybenyang** [comment]
this issue is still reproducing with latest 3.6.1 gradle plugin

**Comment by ilya-shknaj** [comment]
I can't understand, okbuck is a gradle plugin for android. Why it's not compatible with the latest android gradle plugin for almost the year? Okbuck developers using some deprecated Android Studio and don't update it for ages?

**Comment by raviagarwal7** [comment]
Hi Ilya, OkBuck is a gradle plugin used to generate build files for Buck after which you can use buck for building. 
It uses gradle & android-gradle-plugin api's to resolve the build graph and translate that into the buck rules. Unfortunately, the latest version of android-gradle-plugin is not behaving correctly where the build graph resolution now takes more than 15 mins to run (as opposed to few mins currently).

Apologies for not able to update, since it requires substantial amount of debugging and groking the API changes to make it faster.

There is an existing pull request for the same https://github.com/uber/okbuck/pull/905. I due to time constraints I have not been able to get around fixing this yet (will try again to see if I am able to resolve). 

ps: PR's are welcome for a resolution around this issue.

**Comment by onlybenyang** [comment]
hi raviagarwal7, I found a merge from anoopc--fix-agp3.4-api-deprecations to airbnb-current, which update grade plugin to 3.4.2. It's better than 3.2.0.
